### ISSUE TITLE
Can I use the compiled MLI library to implement my own AI algorithm?

### ISSUE THREAD

**Issue by ZhugeKongan** [foss-for-synopsys-dwc-arc-processors/embarc_mli#145]
# Issue Summary
- **Type**:  *Question*
- **Category**: *Library* |*Build System* | *Tools*
- **Priority**: *Urgent* 
- **Release Version**: 2019.09 

--------------------------------------------------------------------------------
# Bug

## Development Environment
- **HOST OS**

     Windows 7, 64Bit 

- **TOOLCHAIN**
    
     ARC GNU 2020.03.
    

- **BOARD**
   
    IoTDK

- **ARC CORE**
     EM9D.

--------------------------------------------------------------------------------
# Question

   I want to implement my own AI model on IOTDK. I learned that the MLI library can only be compiled on MWDT, and I cannot use MWDT. However, the compiled MLI library is provided in the MLI example. Can I use this compiled library on GUN to implement my own AI model? (My model is different from cifar10 in the example)

**Comment by jcampbel** [comment]
Hi @ZhugeKongan 
Do you mean you would like to access the MLI 1.0 prebuilt library for IoTDK, which is found here?
 https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp/tree/embarc_mli/library/embarc_mli under the lib directory?  If so, then this should be fine to use GNU.

Some notes:
Latest version of MLI (1.1, currently in pre-release) has prebuilt libs also, but they have not been tested with GNU and we don't recommend using GNU.
What is the reason you cannot use MetaWare for your application work?  
You can access an evaluation version of MetaWare from here: https://eval.synopsys.com/Home/Index  (choose "MetaWare Development Toolkit" and register)

Best regards,
Jamie

**Comment by ZhugeKongan** [comment]
Your reply helped me a lot, thank you very much
