### ISSUE TITLE
Confusing description of debug modes

### ISSUE THREAD

**Issue by demidan** [foss-for-synopsys-dwc-arc-processors/embarc_mli#30]
Hi Dima,
As you [requested in PR#26](https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_mli/pull/26#discussion_r267373604) I transferring [my comments](https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_mli/pull/26#pullrequestreview-215101717) to this issue.

For easier reference: after documentation restructure, the debug modes description moved to [doc/documents/library_model/hw_dependencies_config.rst](https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_mli/blob/mli_dev/doc/documents/library_model/hw_dependencies_config.rst#function-parameters-examination-and-debug-mli_debug_mode)

In short:
1. I do not like confusing (and not quite true) wording
> function <b>tries</b> to break the execution using assert() function. <b>If</b> the assert() function does not break the execution, function returns error status.
I suggest to 
2. I do not like very repetitive descriptions in one place
3. I think adding descriptive table would make sense

I suggest
1. use wording like `Any violation of data found lead to break on assert()` instead
2. use wording like `The same as DBG_MODE_ASSERT, but before breaking on assert() function prints descriptive message using standard printf() function.`
3. add a table like following:

| Behavior \ Mode | RELEASE | RET_CODES | ASSERT| DEBUG| FULL|
|--------------------|-----------|--------------|---------|--------|------|
| Return codes       |     No      |       Yes         |   Yes     |   Yes   |  Yes  |
| Assertions           |     No      |       No          |   Yes     |   Yes   |  Yes  |
| Extra Assertion    |     No      |       No          |   No     |   No   |  Yes  |
| Messages            |     No      |       No          |   No     |   Yes   |  Yes  |

Best regards,
    Daniil

**Comment by dzakhar** [comment]
Pull request #39 includes changes for this issue. Please, check.

**Comment by demidan** [comment]
Confirming that problem is solved.
