### ISSUE TITLE
Broken link to TF padding scheme

### ISSUE THREAD

**Issue by demidan** [foss-for-synopsys-dwc-arc-processors/embarc_mli#50]
One more minor issue in the documentation:
[the link](https://www.tensorflow.org/api_guides/python/nn) to TensorFlow's 'SAME' padding scheme description got broken.
Looks like TF guys removed that from the latest docs :(

I've found this description (if I'm not mistaken) [in version r1.12](https://www.tensorflow.org/versions/r1.12/api_guides/python/nn?hl=ja#Notes_on_SAME_Convolution_Padding), but formatting there is kinda broken so it's difficult to read.

Maybe we should include this description in our docs? @dzakhar, what do you think?

PS: we reference this in
1. [convolution_2d.rst](../blob/mli_dev/doc/documents/MLI_kernels/convolution_2d.rst) lines 50-52,
1. [pooling_max.rst](../blob/mli_dev/doc/documents/MLI_kernels/pooling_max.rst) lines 34-37, and in
1. [functions.rst](../blob/mli_dev/doc/documents/library_model/functions.rst) line 141 (here 'bookmark-style' reference was not changed to link)

CC: @dyudakov 

Regards,
    Daniil

**Comment by dzakhar** [comment]
Hi Daniil. Actualization of link is definitely required, but I doubt we should re-write it our self until it starts to diverge from the reference one. I found enough info on what is the SAME padding scheme (some of the also references s to broken link of TF). Moreover, TF description formatting is OK again, so I will use the TF link.

**Comment by demidan** [comment]
Hi Dima, thanks for fixing the links!
Since TF guys fixed formatting, and we've fixed their docs version in the link
(so it probably wont be broken again),
I agree that it's Ok to keep it this way.

I've checked that documentation was regenerated and published properly.
Closing this issue.

Regards,
    Daniil
