### ISSUE TITLE
Library build breaks down w/o python

### ISSUE THREAD

**Issue by dzakhar** [foss-for-synopsys-dwc-arc-processors/embarc_mli#60]
Having no python2 in the system I stuck in situation when I can’t build library without re-cloning it from github. The way to reproduce:

``` console
git clone https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_mli.git embarc_mli
cd ./embarc_mli
git checkout Release_1.0_RC2
git checkout master
gmake lib
```
In my case, it leads to next py3 syntactic errors:
```
Traceback (most recent call last):
  File "../gen/mli_krn_conv2d_gen.py", line 1, in <module>
    from func import Func
  File "C:\MyData\Sources\ML_IOT\MLI_Tests\embarc_mli\lib\gen\func.py", line 184
    print "ERROR: unsopported type: " + self.datatype
```
According to it, easiest way to re-build library is to re-clone it. 
Most probably it`s because of designation of source files as targets and consequent changes of python script files (timestamp). In this case gmake invokes re-generation of targets assuming scripts was changed.

Code generation is additional feature, not a mandatory step for the library build. But here we’ve got python2 (*undeclared and required*) dependency, that I believe is not what we want.

**Comment by demidan** [comment]
Hi guys,

since Jacco has turned off the regeneration rules by default in PR #74 
(thus avoiding required python2 dependency)
I guess we can close this issue.

Do you agree?

**Comment by ipozdnov** [comment]
Please close after verification.

**Comment by JaccovG** [comment]
scripts have been updated to be compatible with python 3. (see commit 0bcaea3 )

**Comment by jcampbel** [comment]
Closing this issue
