### ISSUE TITLE
Switch examples to Compact CRT

### ISSUE THREAD

**Issue by anatoly-savchenkov** [foss-for-synopsys-dwc-arc-processors/embarc_mli#65]
Please switch examples to Compact CRT. This will decrease memory requirements without loosing performance. Probably this will allow compilation of some examples with MWDT Lite (32KB code size limit).

**Comment by dzakhar** [comment]
Thanks for the proposal! Before applying, we need to consider it in details.

**Comment by JaccovG** [comment]
Solved in pull request #76
