### ISSUE TITLE
Compilation with LTO / PGO 

### ISSUE THREAD

**Issue by anatoly-savchenkov** [foss-for-synopsys-dwc-arc-processors/embarc_mli#66]
It would be helpful to show how link time or profiling guided optimizations can be enabled for MLI based applications. Please add LTO / PGO infrastructure into Makefiles for the library and examples. Please keep it disabled by default.

**Comment by dzakhar** [comment]
Thanks for the proposal! Before applying, we need to consider it in details.

**Comment by jcampbel** [comment]
This issue will be tracked internally by the MLI Development team.
