### ISSUE TITLE
Document optimal ARC HW IP configuration for MLI

### ISSUE THREAD

**Issue by anatoly-savchenkov** [foss-for-synopsys-dwc-arc-processors/embarc_mli#75]
Customer is asking for ARC HW IP configuration suggestion for an MLI-based application? Could we list and explain the impact for each ARC HW IP configuration option on MLI performance?

**Comment by jcampbel** [comment]
Future versions of MLI will include more details on the hardware requirements in the online documentation.
In the meantime, here is some general guidance:
MLI performs best with EM configurations that have CCMs (closely coupled memories).  This includes DCCM and also XY memories.  The Address Generation Units (AGUs) are also required for best performance, with the largest possible configuration giving the best performance.
